// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertyCare.Infrastructure.Database;

#nullable disable

namespace PropertyCare.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260604125258_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropertyCare.Domain.Entities.Facilities.AssetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitId");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Facilities.AssetTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DefaultSlaHours")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("AssetTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSlaHours = 24,
                            IsDeleted = false,
                            Name = "HVAC",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSlaHours = 8,
                            IsDeleted = false,
                            Name = "Elevator",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSlaHours = 48,
                            IsDeleted = false,
                            Name = "Plumbing",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSlaHours = 24,
                            IsDeleted = false,
                            Name = "Electrical",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSlaHours = 72,
                            IsDeleted = false,
                            Name = "Appliance",
                            TenantId = 1
                        });
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Facilities.BuildingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BuildingTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Facilities.BuildingTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Abrv")
                        .IsUnique();

                    b.ToTable("BuildingTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abrv = "OFFICE",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Office building",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Abrv = "RES",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Residential building",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Abrv = "WH",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Warehouse",
                            TenantId = 1
                        });
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Facilities.UnitEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("TenantId");

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Identity.AppUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Identity.RefreshTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Identity.TenantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "PropertyCare"
                        });
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Identity.UserRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Abrv")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abrv = "ADMIN",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Administrator",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Abrv = "TECH",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Technician",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Abrv = "REP",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Reporter",
                            TenantId = 1
                        });
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.MaintenanceRequestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitId");

                    b.ToTable("MaintenanceRequests", (string)null);
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.RequestCommentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("RequestComments", (string)null);
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.RequestPriorityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("SlaHours")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Abrv")
                        .IsUnique();

                    b.ToTable("RequestPriorities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abrv = "LOW",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Low",
                            SlaHours = 72,
                            TenantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Abrv = "MED",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Medium",
                            SlaHours = 48,
                            TenantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Abrv = "HIGH",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "High",
                            SlaHours = 24,
                            TenantId = 1
                        },
                        new
                        {
                            Id = 4,
                            Abrv = "CRIT",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Critical",
                            SlaHours = 4,
                            TenantId = 1
                        });
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.RequestStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Abrv")
                        .IsUnique();

                    b.ToTable("RequestStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abrv = "NEW",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "New",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Abrv = "ASSIGNED",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Assigned",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Abrv = "IN_PROGRESS",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "In progress",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 4,
                            Abrv = "ON_HOLD",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "On hold",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 5,
                            Abrv = "COMPLETED",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsTerminal = true,
                            Name = "Completed",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 6,
                            Abrv = "CANCELLED",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsTerminal = true,
                            Name = "Cancelled",
                            TenantId = 1
                        });
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.RequestStatusHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FromStatusId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("RequestId");

                    b.HasIndex("ToStatusId");

                    b.ToTable("RequestStatusHistories", (string)null);
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.WorkLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MinutesSpent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkLogs", (string)null);
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.WorkOrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("RequestId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TenantId");

                    b.ToTable("WorkOrders", (string)null);
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.WorkOrderStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Abrv")
                        .IsUnique();

                    b.ToTable("WorkOrderStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abrv = "ASSIGNED",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Assigned",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Abrv = "IN_PROGRESS",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "In progress",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Abrv = "ON_HOLD",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "On hold",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 4,
                            Abrv = "COMPLETED",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsTerminal = true,
                            Name = "Completed",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 5,
                            Abrv = "CANCELLED",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsTerminal = true,
                            Name = "Cancelled",
                            TenantId = 1
                        });
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.System.JobTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Abrv")
                        .IsUnique();

                    b.ToTable("JobTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abrv = "INSPECT",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Inspection",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Abrv = "PREVENT",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Preventive maintenance",
                            TenantId = 1
                        });
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.System.NotificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.System.ScheduledJobEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("ScheduledJobs", (string)null);
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Facilities.AssetEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Facilities.AssetTypeEntity", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Facilities.UnitEntity", "Unit")
                        .WithMany("Assets")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetType");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Facilities.AssetTypeEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Facilities.BuildingEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Facilities.BuildingTypeEntity", "BuildingType")
                        .WithMany("Buildings")
                        .HasForeignKey("BuildingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuildingType");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Facilities.BuildingTypeEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Facilities.UnitEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Facilities.BuildingEntity", "Building")
                        .WithMany("Units")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Identity.AppUserEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Identity.UserRoleEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Identity.RefreshTokenEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Identity.AppUserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Identity.UserRoleEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.MaintenanceRequestEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Facilities.AssetEntity", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropertyCare.Domain.Entities.Facilities.BuildingEntity", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Identity.AppUserEntity", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Maintenance.RequestPriorityEntity", "Priority")
                        .WithMany("Requests")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Maintenance.RequestStatusEntity", "Status")
                        .WithMany("Requests")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Facilities.UnitEntity", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("Building");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Priority");

                    b.Navigation("Status");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.RequestCommentEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Maintenance.MaintenanceRequestEntity", "Request")
                        .WithMany("Comments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Identity.AppUserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.RequestPriorityEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.RequestStatusEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.RequestStatusHistoryEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Identity.AppUserEntity", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Maintenance.RequestStatusEntity", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropertyCare.Domain.Entities.Maintenance.MaintenanceRequestEntity", "Request")
                        .WithMany("StatusHistory")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Maintenance.RequestStatusEntity", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("FromStatus");

                    b.Navigation("Request");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.WorkLogEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Maintenance.WorkOrderEntity", "WorkOrder")
                        .WithMany("WorkLogs")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.WorkOrderEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Identity.AppUserEntity", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Maintenance.MaintenanceRequestEntity", "Request")
                        .WithMany("WorkOrders")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Maintenance.WorkOrderStatusEntity", "Status")
                        .WithMany("WorkOrders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("Request");

                    b.Navigation("Status");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.WorkOrderStatusEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.System.JobTypeEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.System.NotificationEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Identity.AppUserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.System.ScheduledJobEntity", b =>
                {
                    b.HasOne("PropertyCare.Domain.Entities.System.JobTypeEntity", "JobType")
                        .WithMany("ScheduledJobs")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyCare.Domain.Entities.Identity.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobType");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Facilities.AssetTypeEntity", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Facilities.BuildingEntity", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Facilities.BuildingTypeEntity", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Facilities.UnitEntity", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Identity.AppUserEntity", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Identity.TenantEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Identity.UserRoleEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.MaintenanceRequestEntity", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("StatusHistory");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.RequestPriorityEntity", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.RequestStatusEntity", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.WorkOrderEntity", b =>
                {
                    b.Navigation("WorkLogs");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.Maintenance.WorkOrderStatusEntity", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("PropertyCare.Domain.Entities.System.JobTypeEntity", b =>
                {
                    b.Navigation("ScheduledJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
